### ISSUE TITLE
紐付き先のTryカードを複数もつK,Pカードを削除しても、紐付き先のTryカードが１枚しか消えない

### ISSUE THREAD

**Issue by luckyriverr** [HanaLucky/KPTer#127]
#### DONE
- バグ解消
#### TASK
- [ ] リレーションのあるべき関係を整理（一対一、N対N、１対N、N対１）
- [ ] bug修正

**Comment by hanaori** [comment]
①

> class func findFromCardRelation(card: Card) -> Card?
- 上記メソッドの名前を-Relationsに変更
- 上記の戻り値をArray<Card>に変更

②

> class func deleteCardRelation(tryCard: Card)
- 上記メソッドの名前を-Relationsに変更
- 引数をArray<Card>に変更
