### ISSUE TITLE
KPTer公開

### ISSUE THREAD

**Issue by luckyriverr** [HanaLucky/KPTer#197]
#### DONE
- KPTerがストアに並ぶ
#### TASK
- [x] screenshotsを埋める
  - [x] デザイン考案する　Doing
- [x] Descriptionを埋める
- [x] カテゴリーを埋める
- [x] キーワードを埋める
- [x] サポートURLを埋める
- [x] マーケティングURLを埋める→いらない
- [x] コピーライトを埋める @luckyriver0
  - [x] HanaLuckyのままでいいのか？
- [x] 販売元（seller）の名前を替えられるか確認　@luckyriver0 
- [x] 不明な項目に何を入力するか知らべる　@hanaori

**Comment by hanaori** [comment]
がんばったー！
![itunes connect](https://cloud.githubusercontent.com/assets/7506598/16360379/d336946c-3b9a-11e6-942e-e82707589aa7.png)
