### ISSUE TITLE
必須項目が未入力の場合、Saveボタンを非活性にする

### ISSUE THREAD

**Issue by luckyriverr** [HanaLucky/KPTer#23]
### 対象画面
- [ ] ボード追加・編集画面
- [ ] カード追加・編集画面
### Ref

http://d.hatena.ne.jp/seikenn/20120906/UIButton

**Comment by luckyriverr** [comment]
申し訳ないです。。。

**Comment by hanaori** [comment]
No Problemだよー！
![image](https://cloud.githubusercontent.com/assets/7506598/14642724/8f10114e-0686-11e6-9f0a-ce0b29ca1898.png)
