### ISSUE TITLE
われわれのKPTerの各画面イメージをevernoteに春

### ISSUE THREAD

**Issue by luckyriverr** [HanaLucky/KPTer#67]
@hanaori さんへ
動くところだけevernoteにデモ画像を貼ってみた。同じものを↓にもはっているがいかがだろう。
![kpter-image](https://cloud.githubusercontent.com/assets/16001636/14352798/38b0d0b4-fd11-11e5-9d62-becedefe4581.gif)

**Comment by hanaori** [comment]
素敵だと思いますです！
